"""
Tests for the timings -> (protocol, address, command) decoder.

Every test here is self-contained: signals are generated by ir_dongle.protocols' encoders and
fed back through the decoder, so nothing external is needed.

Each one encodes a bug that actually bit during development -- see the docstrings.

Run: python -m pytest tests/test_ir_decode.py -q
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ir_dongle.ir_decode import decode, frame_gap_threshold, split_frames
from ir_dongle.protocols import IRProtocol, ProtocolType


# --------------------------------------------------------------------------------------
# round-trips through the independent encoders
# --------------------------------------------------------------------------------------

def test_nec_round_trip():
    for addr in (0x00, 0x04, 0x7F, 0xEF):
        for cmd in (0x00, 0x08, 0x15, 0xAA, 0xFF):
            d = decode(IRProtocol.encode_nec(addr, cmd))
            assert d.protocol == "NEC", f"addr={addr:#x} cmd={cmd:#x} -> {d.protocol}"
            assert (d.address, d.command) == (addr, cmd), f"{d} != addr {addr} cmd {cmd}"


def test_nec_is_lsb_first_per_byte():
    """REGRESSION: assembling bits MSB-first bit-reverses every byte, so address 0x04
    decoded as 0x20 and command 0x08 as 0x10. NEC sends each byte LSB-first."""
    d = decode(IRProtocol.encode_nec(0x04, 0x08))
    assert (d.address, d.command) == (0x04, 0x08)


def test_sirc_round_trip():
    for addr, cmd in ((1, 21), (1, 18), (16, 5), (1, 0)):
        d = decode(IRProtocol.encode_signal(ProtocolType.SIRC, addr, cmd).timings)
        assert (d.protocol, d.address, d.command) == ("SIRC", addr, cmd), d


# --------------------------------------------------------------------------------------
# structural invariants
# --------------------------------------------------------------------------------------

def test_sirc_leader_is_detected_from_the_mark_alone():
    """REGRESSION: Sony's leader SPACE is the same length as its bit space, so a leader test
    that demands a long mark AND a long space never fires. The 2400us leader mark then reads
    as data and every bit shifts by one (command 21 decoded as 43, address 1 as 2)."""
    d = decode(IRProtocol.encode_signal(ProtocolType.SIRC, 1, 21).timings)
    assert d.bits == 12, f"SIRC12 expected, got {d.bits} bits"
    assert (d.address, d.command) == (1, 21)


def test_pulse_length_keeps_its_final_mark():
    """REGRESSION: a trailing lone mark is a STOP bit in pulse-distance coding but the LAST
    DATA BIT in pulse-length coding. Trimming it unconditionally made every SIRC frame
    11 bits wide."""
    for cmd in (21, 0, 18):
        assert decode(IRProtocol.encode_signal(ProtocolType.SIRC, 1, cmd).timings).bits == 12


def test_biphase_is_recognised():
    """RC5 is bi-phase: every run is one or two half-bit units."""
    d = decode([889] * 28)
    assert d.family == "BiPhase", f"expected BiPhase, got {d.family}"


def test_rc5_round_trip():
    """REGRESSION: RC5's first start bit is a 1, i.e. space-then-mark, but a capture begins at
    the first MARK so the leading half-bit is never recorded. Without compensating, every cell
    misaligns and RC5 frames decode as junk."""
    d = decode(IRProtocol.encode_signal(ProtocolType.RC5, 5, 12).timings)
    assert d.protocol in ("RC5", "RC5X"), d
    assert d.address == 5, d


# --------------------------------------------------------------------------------------
# framing
# --------------------------------------------------------------------------------------

def test_frame_gap_threshold_adapts_to_long_data_spaces():
    """REGRESSION: a fixed 5000us frame-split destroys protocols whose DATA spaces exceed it.
    This shape -- 224us marks, 4848us = 0, 7328us = 1 -- collapsed into 2-element fragments
    that decoded as nothing."""
    timings = [224, 4848, 224, 7328, 224, 7328, 224, 4848, 224, 7328, 224, 4848] * 2
    assert frame_gap_threshold(timings) == float("inf"), (
        "4848 and 7328 are both data spaces; neither is a frame gap"
    )
    d = decode(timings)
    assert d.notes != "too short", f"still degenerate: {d}"
    assert d.family == "PulseDistance"


def test_nec_frame_gap_is_still_split():
    one = IRProtocol.encode_nec(0x04, 0x08)
    assert frame_gap_threshold(one + [40000] + one) < 40000


def test_repeated_transmission_decodes_as_one_frame():
    """A press is sent as the frame repeated N times; classification looks at one frame and
    reports how many there were."""
    d = decode(IRProtocol.encode_signal(ProtocolType.SIRC, 1, 21).timings * 5)
    assert d.frames == 5, f"expected 5 frames, got {d.frames}"
    assert (d.address, d.command) == (1, 21)


# --------------------------------------------------------------------------------------
# the inter-frame gap -- only a real receiver can catch this one
# --------------------------------------------------------------------------------------

def test_encoded_signals_carry_their_inter_frame_gap():
    """REGRESSION, and one nothing offline could have caught.

    The bare encoders emit only a frame's own marks and spaces, ending on a ~600us space.
    Repeating that N times -- which is how a button press is sent -- produced N frames with no
    silence between them, and the TV ignored every one. The signal still DECODED perfectly, so
    every offline check passed while the code was unusable on real hardware.

    encode_signal pads each frame out to its protocol's standard period.
    """
    for proto, period in ((ProtocolType.SIRC, 45000),
                          (ProtocolType.NEC, 108000),
                          (ProtocolType.RC5, 114000)):
        sig = IRProtocol.encode_signal(proto, 1, 21)
        assert sum(sig.timings) == period, (
            f"{proto.value}: frame period {sum(sig.timings)}us, expected {period}us"
        )
        assert sig.timings[-1] >= IRProtocol.MIN_FRAME_GAP_US, (
            f"{proto.value}: last element {sig.timings[-1]}us is not an inter-frame gap"
        )
        assert len(split_frames(sig.timings * 3)) == 3, "repeats fused together"


def test_empty_and_garbage_are_reported_not_crashed():
    assert decode([]).protocol == "Unknown"
    assert decode([1, 2]).protocol == "Unknown"
    assert decode([500] * 3).protocol in ("Unknown", "BiPhase", "PulseDistance")


if __name__ == "__main__":
    import traceback
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS  {fn.__name__}")
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"FAIL  {fn.__name__}: {e}")
            traceback.print_exc()
    print(f"\n{len(fns)-failed}/{len(fns)} passed")
    sys.exit(1 if failed else 0)
